-- CREATE USER
CREATE ROLE "testDB" LOGIN
  ENCRYPTED PASSWORD 'md553ffb125586759e24e875d14486a5b1b' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

-- CREATE DATABASES
CREATE DATABASE atos
  WITH OWNER = "testDB"
 ENCODING = 'UTF8' TABLESPACE = pg_default
 CONNECTION LIMIT = -1;
CREATE DATABASE senercon
  WITH OWNER = "testDB" ENCODING = 'UTF8' TABLESPACE = pg_default
 CONNECTION LIMIT = -1;
CREATE DATABASE siemens
  WITH OWNER = "testDB" ENCODING = 'UTF8'
 TABLESPACE = pg_default CONNECTION LIMIT = -1;